#trigger: ["*"]
#pr: ["*"]

pool:
  vmImage: ubuntu-18.04

variables:
  RUSTFLAGS: -Dwarnings

jobs:
  # Test minictrl-web
  - template: ci/azure-test-stable.yml
    parameters:
      rust: 1.42.0
      bins:
        - minictrl-agent
        - minictrl-cli
        - minictrl-web

  # Check formatting
  - template: ci/azure-rustfmt.yml
    parameters:
      rust: stable
      name: rustfmt

  # Lint using clippy
  - template: ci/azure-clippy.yml
    parameters:
      rust: stable
      name: clippy