[package]
name = "minictrl"
version = "0.1.0"
authors = ["Jacob Jenner Rasmussen <jacob@jener.dk>"]
edition = "2018"

[dependencies]
diesel = { version = "1.4.3", features = ["postgres", "network-address"] }
diesel-derive-enum = { version = "0.4.4", features = ["postgres"] }
dotenv = "0.11.0"
ipnetwork = "0.15.0"
serde_json = "^1.0.45"
serde = { version = "1.0", features = ["derive"] }
actix = "0.9.0"
actix-web = "2.0"
actix-rt = "1.0"
actix-cors = "0.2.0"
juniper = { git = "https://github.com/graphql-rust/juniper", rev = "547cf3e36fa0532476295186b86954fab3a258f6", features = ["async"] }
futures = "0.3"
