version: '3'
services:
  database:
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=minictrl
      - POSTGRES_USER=minictrl
      - POSTGRES_DB=minictrl
    ports:
      - "5432:5432"
  minictrl:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://minictrl:minictrl@database/minictrl
